### ISSUE TITLE
Le filtre par Option ne fonctionne pas 

### ISSUE THREAD

**Issue by azudaire** [asdoria/AsdoriaSyliusFacetFilterPlugin#3]
Bonjour, 
 Le filtre par Option simple ne fonctionne pas. Tous les produits sortent peu importe l'option choisie.

**Comment by pvasdoria** [comment]
Hello, I answer in English but you can continue to communicate in French if you like.
I fixed the bug in the 0.1.1 release and packaged the 0.1.2 to support sylius 1.12 with symfony 6
Sincerely
