### ISSUE TITLE
Field type not displayed in backoffice

### ISSUE THREAD

**Issue by ghost** [asdoria/AsdoriaSyliusFacetFilterPlugin#6]
Hello i'm trying to use the bundle for filtering product but in backoffice i can not retrieve the list of field type into  Configuration >  Facet Filters and create new.
The following route is: `/admin/facet-filter/{id}/facets/new/taxon` Field Type is empty.

Help please. Thank you

**Comment by pvasdoria** [comment]
Hello, the problem comes from the namespace of your entity Taxon it should be "App\Entity\Taxonomy\Taxon".
Can you play this cmd and give me the result : php bin/console debug:container --parameters | grep -i 'sylius.model.taxon.class'
what version of sylius are you under ?
Sincerely
